### ISSUE TITLE
Create dbt project including readme file

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/dbt-airflow-test#1]
tasks : https://n-abledev.atlassian.net/browse/DA-2561?atlOrigin=eyJpIjoiMmZkNzNjZDk2YmIzNDBlMTljOWY0N2Q2YTMwYTNiM2EiLCJwIjoiaiJ9

https://n-abledev.atlassian.net/browse/DA-2562?atlOrigin=eyJpIjoiOGYxODFkMGU2NTY1NGZkMjk0YmMzMGViNDU1YWFkMzciLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #2 from koshitha-nable/ka/feature/001/create_project
