### ISSUE TITLE
create dag file to run jobs

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/dbt-airflow-test#3]
Task : https://n-abledev.atlassian.net/browse/DA-2567?atlOrigin=eyJpIjoiMWI5YjNiMTEyY2E1NGJiNjhkNzk3ZDhlY2FkMjBmNWQiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #4 from koshitha-nable/ka/feature/003/create_dag
