### ISSUE TITLE
create dag for failed senarios and monitor

### ISSUE THREAD

**Issue by koshitha-nable** [koshitha-nable/dbt-airflow-test#5]
tasks:
https://n-abledev.atlassian.net/browse/DA-2560?atlOrigin=eyJpIjoiMDFiMTUwN2M0ZDJkNDEzZWFjMzBmYWY1NTgwMDY5NWMiLCJwIjoiaiJ9

https://n-abledev.atlassian.net/browse/DA-1799?atlOrigin=eyJpIjoiOGRjMDYxYmQ4NDk3NGNmODg2NWZmYzc3NzhmMjg3MTAiLCJwIjoiaiJ9

**Comment by piranavan-nable** [comment]
Merge pull request #6 from koshitha-nable/ka/feature/005/create_dag_failed
